# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='family_id',
        ),
    ]
