# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaymessage',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
