# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0002_remove_member_family_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='indv_id',
            new_name='indvid',
        ),
    ]
