# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0003_auto_20170904_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlog',
            old_name='indv_id',
            new_name='indvid',
        ),
    ]
