# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0004_auto_20170904_0913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Child',
        ),
    ]
