# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0005_auto_20170905_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('age', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('plain_text', models.CharField(max_length=65000)),
                ('html', models.CharField(max_length=65000)),
                ('attachment', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agist.Message'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
