# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0006_auto_20170905_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='when_performed',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
