# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0007_auto_20170905_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='html',
            field=models.TextField(max_length=65000),
        ),
        migrations.AlterField(
            model_name='message',
            name='plain_text',
            field=models.TextField(max_length=65000),
        ),
    ]
