# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0009_auto_20170905_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdaymessage',
            old_name='html',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='birthdaymessage',
            name='plain_text',
        ),
    ]
