# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0010_auto_20170906_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaymessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
