# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0011_auto_20170906_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='indvid',
        ),
        migrations.DeleteModel(
            name='ActionLog',
        ),
    ]
