# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0012_auto_20170906_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdaymessage',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='birthdaymessage',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
