# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agist', '0013_auto_20170913_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaymessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='birthdaymessage',
            name='content',
            field=models.TextField(),
        ),
    ]
