# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F2FSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
            ],
            options={
                'verbose_name': 'F2F Setting',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hosts', models.CharField(max_length=100)),
                ('leaders', models.CharField(blank=True, max_length=100, null=True)),
                ('leader_email', models.EmailField(max_length=254)),
                ('leader_phone', models.CharField(max_length=15)),
                ('day_of_week', models.CharField(choices=[(b'Sunday', b'Sunday'), (b'Monday', b'Monday'), (b'Tuesday', b'Tuesday'), (b'Thursday', b'Thursday')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('order_field', models.IntegerField()),
            ],
            options={
                'ordering': ['order_field'],
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.CharField(default=b'adult_education', max_length=20)),
                ('dow_first_choice', models.CharField(blank=True, choices=[(b'Sunday', b'Sunday'), (b'Monday', b'Monday'), (b'Tuesday', b'Tuesday'), (b'Thursday', b'Thursday')], max_length=100, null=True)),
                ('dow_second_choice', models.CharField(blank=True, choices=[(b'Sunday', b'Sunday'), (b'Monday', b'Monday'), (b'Tuesday', b'Tuesday'), (b'Thursday', b'Thursday')], max_length=100, null=True)),
                ('student_class', models.CharField(blank=True, choices=[(b'Freshman', b'Freshman'), (b'Sophomore', b'Sophomore'), (b'Junior', b'Junior'), (b'Senior', b'Senior'), (b'Grad Student', b'Grad Student')], max_length=100, null=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('spouse_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(default=b'TX', max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('comments', models.CharField(blank=True, max_length=400, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('send_member_email', models.BooleanField(default=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='f2fsignup.Group')),
            ],
        ),
    ]
