# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2fsignup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='spouse_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
