# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2fsignup', '0002_member_spouse_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
