# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2fsignup', '0003_member_spouse_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='spouse_dob',
        ),
        migrations.RemoveField(
            model_name='member',
            name='spouse_email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='spouse_first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='spouse_last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='spouse_phone',
        ),
    ]
