# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2fsignup', '0005_auto_20170917_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='f2fsettings',
            options={'verbose_name': 'F2F Settings'},
        ),
        migrations.RemoveField(
            model_name='f2fsettings',
            name='start_date',
        ),
        migrations.AddField(
            model_name='f2fsettings',
            name='attribute',
            field=models.CharField(default='start_date', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='f2fsettings',
            name='value',
            field=models.CharField(default='09/10/2017', max_length=255),
            preserve_default=False,
        ),
    ]
