# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2fsignup', '0006_auto_20170917_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.CharField(max_length=255)),
                ('limit', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='f2fsettings',
            options={'verbose_name': 'F2F Setting'},
        ),
    ]
