# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2fsignup', '0009_auto_20170917_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministrylimit',
            name='ministry',
            field=models.CharField(max_length=255),
        ),
    ]
