# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f2fsignup', '0010_auto_20170917_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('limit', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MinistryLimit',
        ),
        migrations.AlterField(
            model_name='member',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f2fsignup.Ministry'),
        ),
    ]
