# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2fsignup', '0011_auto_20170917_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name_plural': 'ministries'},
        ),
    ]
