# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2fsignup', '0012_auto_20171017_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
