# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayMessage',
            fields=[
                ('age', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('indvid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dob', models.DateField()),
            ],
        ),
    ]
