# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faithpath', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faithpath.Child')),
            ],
        ),
        migrations.AlterField(
            model_name='birthdaymessage',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faithpath.BirthdayMessage'),
        ),
    ]
